### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by Pastim** [hvdwolf/OsmAnd-UKpostcodes#1]
I'm sure I'm being very dim, but I can't get this search to work. I'm using OSMAND+ 2.7.5 (on lineageos 14.1). 

I have downloaded and unzipped all the postcode files into the osmand+ files directory on my mobile.

I have added a custom filter for the user defined postcodes, so there is now a user defined category.  This shows my local postcodes, including some defined in your files.  OK so far.  

But how do I search for a postcode somewhere else?  I never find any, which search method I try to use.  If you could give detailed instructions on how to use this, it would be a great help to me.

**Comment by Pastim** [comment]
Sorry, but this is driving me nuts.  I now, somehow, have all the postcodes on the display, but I still can't search for them.  Help!

**Comment by hvdwolf** [comment]
I only use the overall United-kingdom_postcodes_poi_europe.obf because it is by far the fastest and works excellent with the new search screens.
When I open the search screen I simply type in "CT14 8HB" (Deal, Kent) or "ex34 7aw" (Woolacombe, Devon) or "yo62 5bs" (Helmsley, North-Yorkshire). (some wildly chosen PCs from holiday destinations)

When searching from the Netherlands I sometimes get a "Nothing found" and below it the button to "enlarge the search area". when I click that I do get the search result (and sometimes you need to click it again).

**Comment by Pastim** [comment]
Thanks.  I have deleted the England, wales, scotland and ireland files and kept the UK file.

It still doesn't work on my mobile. What precisely do I have to do to get it to install it and get it to work?  

Sorry for being so slow, but there are is more than one way to search, and none of them seem to work.  As an aside, I seem to have lost the display of postcodes on the maps.

**Comment by Pastim** [comment]
I think I may have found out what is happening.

If I enter a postcode that is not in the standard files, the search fails to find it, stops, and shows other  postcodes in the same are that are in the standard files.  

To search for an Oxford postcode from where I am it is around 36 miles away and many other postcodes are shown, but not the one I ask for.    If I then go to the bottom of the list (which can be very long) and 'increase search radius' all of a sudden the additional user-defined postcodes are found.  In this case, 38 miles away.  

So why don't the user-defined postcodes get scanned unless I 'increase search radius' , even though other postcodes at the same distance are found?

I might add this even happens for my own postcode when I am at home.

**Comment by hvdwolf** [comment]
The only thing you have to do is copy the obf file in the same folder where you have your other obf files.
That is really everything there is to it.
Simply press search from the menu and type in a postcode in the white top bar. There is no need for the selection of history, category or address, especially NOT address.
Again: When you enter the search screen it (mostly) defaults to the left "history" pane with a white bar on top. In that white bar you type the postcode.

**Edit:** note that the postcode in the Address pane of the search screen is really a postcode taken from the addresses. My file is a POI file where the POIs have the names of the postcodes, like you would search for "Tower Bridge" or "Eiffel Tower". I will mention that on the download site

**Comment by Pastim** [comment]
Thanks.  

Do you have any idea why I have to wait until all normal postcodes have been found similar to the one I enter, then 'increase search radius'?  The postcode I enter is at much the same distance, but it behaves as if there is no such user defined postcode until I increase the search radius.  It's very odd, and explains why I was fooled into thinking it wasn't working at all.

Or is there some setting where I can override the search radius check?

**Comment by hvdwolf** [comment]
I don't know. I used to be quite active with OsmAnd, but the past 1½ year I hardly paid attention.
Currently I only use it for hiking.

**Comment by Pastim** [comment]
That's what I use it for mostly, but once in a while I need to look up a friend's place or a shop somewhere.  

Anyway, thanks very much for your help, and for the postcodes file.  I'll close this 'issue' now.
