### ISSUE TITLE
Crash at end of 02_create_postcode_map.py

### ISSUE THREAD

**Issue by gb-dursley** [hvdwolf/OsmAnd-UKpostcodes#4]
_I'm trying to create the postcode POI file on my Linux (Mint 18.3) laptop because it is 10x faster and has twice the RAM of my Android tablet (and Android drives me nuts for doing anything in the least technical!), intending to copy the Postcode POI file onto the Tablet's 128Gb microSD card.
Following your instructions carefully and setting_ 
  OMC = "/home/gba/Downloads/OsmAndMapCreator"
 _all goes well until I run:-_
  
gba@gba-PORTEGE-R830 ~/Downloads/OsmAnd-UKpostcodes $ ./02_create_postcode_map.py

== Now  make the POI UK_postcode map  ==

== Now  running OsmAndMapCreator utilities to create the UK_postcodes_poi_europe.obf POI map ==
Traceback (most recent call last):
  File "./02_create_postcode_map.py", line 51, in <module>
    shutil.copyfile(os.path.join(OMC,'Uk_postcodes_poi_europe.obf'), os.path.join(realfile_dir,'UK_postcodes_poi_europe.obf'))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/gba/Downloads/OsmAndMapCreator/Uk_postcodes_poi_europe.obf'

_Folder_ 
/home/gba/Downloads/OsmAndMapCreator/
_now contains_
/fonts
/lib
batch.xml
inspector.bat
inspector.sh
logging.properties
OsmAndMapCreator.bat
OsmAndMapCreator.jar
OsmAndMapCreator.sh
OsmAndMapCreator-main.zip
UK_postcodes_batch.xml
UK_postcodes_poi_europe.osm.pbf
utilities.bat
utilities.sh

_The last 4 lines of_ 
02_create_postcode_map.py
_read_
os.chdir(OMC)
print("\n== Now  running OsmAndMapCreator utilities to create the UK_postcodes_poi_europe.obf POI map ==")
#os.system(os.path.join(OMC,UTIL) + ' generate-poi UK_postcodes_poi_europe.osm.pbf')
shutil.copyfile(os.path.join(OMC,'Uk_postcodes_poi_europe.obf'), os.path.join(realfile_dir,'UK_postcodes_poi_europe.obf'))

_The last-but-one line, which seems to generate the .obf file, appears to be commented-out?_

**Comment by hvdwolf** [comment]
I am sorry. You are completely right. When I tested my last fix I disabled the map creation as that is the most lengthy step.
Now corrected. It only requires removal of the # hash sign.
I also added an extra comment but that's not really relevant for the script.
